@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMCwiZXhwIjoxNjU3MjI1Nzg0fQ.4GYXiDceT7bWRXfaaCx2L-nJ610j6BCfGFJJvyLHUZs

####################################################
### Resorts Index
GET http://localhost:3000/resorts.json

### Resorts Show
GET http://localhost:3000/resorts/4.json

####################################################
### Events Index
GET http://localhost:3000/events.json

### Events Show
GET http://localhost:3000/events/1.json

### Events Create
POST http://localhost:3000/events.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "resort_id": 1,
  "name": "Sample event",
  "date": "1/01/23",
  "description": "Sample event description",
  "link": "http://www.bridgerbowl.com"
}

####################################################
### Conditions_Report Index
GET http://localhost:3000/conditions_reports.json

### Conditions_Report Create
POST http://localhost:3000/conditions_reports.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "user_id": 10,
  "resort_id": 1,
  "rating": 5,
  "comment": "Just incredible up there"
}

####################################################
### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "username": "bb",
  "email": "brad.bb.bell@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Users show
GET http://localhost:3000/users/10.json

### Users update
PATCH http://localhost:3000/users/10.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

####################################################
### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "brad.bb.bell@gmail.com",
  "password": "password"
}

####################################################
### To Do Resorts index
GET http://localhost:3000/to_do_resorts

### To Do Resorts create
POST http://localhost:3000/to_do_resorts
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "resort_id": 10,
  "user_id": 10
}

### To Do Resorts destroy
DELETE http://localhost:3000/to_do_resorts/15.json
Authorization: Bearer {{jwt}}

####################################################
### Favorite_Resort Index
GET http://localhost:3000/favorite_resorts

### Favorite_Resort Create
POST http://localhost:3000/favorite_resorts
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "user_id": 10,
  "resort_id": 3
}

### Favorite Resorts destroy
DELETE http://localhost:3000/favorite_resorts/6.json
Authorization: Bearer {{jwt}}

####################################################
### Fun_Facts Index
GET http://localhost:3000/fun_facts

### Fun_Facts Show
GET http://localhost:3000/fun_facts/1.json