@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMCwiZXhwIjoxNjU3MTI3ODAxfQ.oT7P2sVaJkeodcAsr_3ESW_poXmgVJBilXz1czg-tbk

####################################################
### Resorts Index
GET http://localhost:3000/resorts.json

### Resorts Show
GET http://localhost:3000/resorts/1.json

####################################################
### Events Index
GET http://localhost:3000/events.json

### Events Show
GET http://localhost:3000/events/1.json

### Events Create
POST http://localhost:3000/events.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "resort_id": 1,
  "name": "Sample event",
  "date": "1/01/23",
  "description": "Sample event description",
  "link": "http://www.bridgerbowl.com"
}

####################################################
### Conditions_Report Index
GET http://localhost:3000/conditions_reports.json

### Conditions_Report Create
POST http://localhost:3000/conditions_reports.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "user_id": 10,
  "resort_id": 1,
  "rating": 5,
  "comment": "Just incredible up there"
}

####################################################
### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "username": "bb",
  "email": "brad.bb.bell@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Users show
GET http://localhost:3000/users/10.json

### Users update
PATCH http://localhost:3000/users/10.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

####################################################
### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "brad.bb.bell@gmail.com",
  "password": "password"
}